# Generated by Django 6.0.1 on 2026-03-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_archivos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivos',
            options={'ordering': ['-created'], 'verbose_name': 'Archivo', 'verbose_name_plural': 'Archivos'},
        ),
        migrations.RenameField(
            model_name='archivos',
            old_name='decripcion',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='archivos',
            name='update',
        ),
        migrations.AddField(
            model_name='archivos',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='comentariocontacto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
